### ISSUE TITLE
Map Overlays

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#30] opened 2021-04-26 16:06 UTC
Yep, generic path overlays are possible:

https://leafletjs.com/examples/quick-start/example-overlays.html

I was actually already planning on working on this already, but want to get the marker stuff nailed down first.

_Originally posted by @valentine195 in https://github.com/valentine195/obsidian-leaflet-plugin/issues/27#issuecomment-826959034_

**Comment by Moonbase59** [comment] 2021-05-20 08:22
Maybe we could come back to that after
- https://github.com/valentine195/obsidian-leaflet-plugin/issues/25#issuecomment-844832601
- https://github.com/valentine195/obsidian-leaflet-plugin/issues/56

My use case:

I have Home Automation using _[Home Assistant](https://www.home-assistant.io/)_, and it has defined "areas". Say, around 50 or 100 meters around my house, it knows that I’m coming home (or leaving) and starts doing automations (like turning lights on or off), and I’d like to show this area (circle around the house) on my map.

Ideally, this could also become a YAML entry and be gotten from there (like the "people" note for myself having something like an "activation radius" entry, or interesting locations or friend’s "people" notes having a "nearby" radius in their YAML, that would somehow make the map to show a circle around the place.

I already use `nearby: 50 km` for location and people notes, to have a value for their "built-in" Dataview tables that show places and other people of interest nearby. This features the same units we use, i.e. *m*, *km*, *mi* and *yd*.

Not wanting you to become "my personal programmer", but I enjoy brainstorming with you, and the beautiful results that come out of it, most probably also useful for a lot of other users.

Amazing work you’re doing, totally appreciate it!

**Comment by valentine195** [comment] 2021-05-20 12:30
I haven't begun work on this feature yet because I was still debating with myself on the syntax I would like to use. I like your proposed syntax - I think I'll adopt it.

I'm trying to keep feature parity between things defined in the code block (or in notes, but this syntax would be the same) and things you can directly create on the map. For this feature, I was thinking one of two things:

1. Adding a "drawing mode" control button that would add a drawing bar with the different shapes (circle, square/rect, triangle, etc) and color controls
2. Adding a <kbd>Mod</kbd> - right click menu that would show _shapes_ instead of _marker types_

Thoughts?

**Comment by Moonbase59** [comment] 2021-05-21 12:24
Offhand, without deep thinking:

- feature parity: yep, a good thought. I tend to neglect one or the other, at times.
- Overall, don’t make it too complicated. I think two things rule: Basic Obsidian should always feel fast and "snappy", and ease-of-use is key. After all, you might come back weeks after and _still_ want to be able to use stuff without re-learning. (So far: job well done!)
- shapes instead of marker types: good idea, I think.
- drawing mode: yeah, well … (not too complicated if possible, no second paint app). After asking a few of my friends, most would probably ever only use "circle". (I might have missed the shape type in my YAML idea above.) All of these agreed they’d be happy with a structure as proposed (putting the info in the notes’ YAML), use Dataview to make a list of "nearby" things, and watch circles overlap on the map to pinpoint areas of interest within the intersections. Maybe only different fill colours and/or outlines to visualize the difference between people, locations, and so on.
- The only other thing people pointed me at was _areas_, like the outline of a country, county, city. Most probably _much_ too complicated for this little map thing! If ever, it would probably mean using _GeoJSON_ and _[ESRI Shapefiles](https://en.wikipedia.org/wiki/Shapefile)_. Nice feature, but overkill here, I feel. I also think that Obsidian as a whole and maps insofar possible should ideally be able to run without Internet connection as far as possible—a fact many seem to forget. This won’t work for real world maps, of course.

Just in case, I attach a JSON file describing the "Landkreis Günzburg" district in Bavaria, Germany (where I live). If such should ever be used, I think it must be generated elsewhere and only _imported_ into Obsidian Leaflet somehow.

[geo-lk-günzburg.json.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6522422/geo-lk-gunzburg.json.zip)

**Comment by valentine195** [comment] 2021-05-21 12:45
> shapes instead of marker types: good idea, I think

Also significantly easier than a "drawing mode" :)

> After asking a few of my friends, most would probably ever only use "circle".

I could always just start with circle, but build it internally to something that could expand in the future if people end up requesting additional (basic) shapes.

 > The only other thing people pointed me at was areas, like the outline of a country, county, city. Most probably much too complicated for this little map thing! If ever, it would probably mean using GeoJSON and ESRI Shapefiles. Nice feature, but overkill here, I feel. I also think that Obsidian as a whole and maps insofar possible should ideally be able to run without Internet connection as far as possible—a fact many seem to forget. This won’t work for real world maps, of course.

Interesting idea. I think doing this like I do with images (a parameter with a path/wikilink to the GeoJSON file stored locally) would work for this easily enough. Leaflet has pretty good GeoJSON support built in (see [this](https://leafletjs.com/examples/choropleth/)).

**Comment by Moonbase59** [comment] 2021-05-21 12:53
Yeah, but please don’t overcommit yourself on that GeoJSON stuff (I know myself …)—especially on lower-end machines, it tends to slow down the machine _considerably_! (And if you got _one_ area working, you want more and more … until everything crawls. It’s only poor Javascript, after all.)

For playing around with, I’ll include a shapefile zip and the OGRE-generated GeoJSON for my district. ;-) I’m not sure if these are generated correctly, though!

[geo-lk-günzburg-2-geojson.json.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6522578/geo-lk-gunzburg-2-geojson.json.zip)
[geo-lk-günzburg-2-shapefile.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6522579/geo-lk-gunzburg-2-shapefile.zip)

**Comment by valentine195** [comment] 2021-05-24 17:35
### 3.11.0
-   Added basic circle map overlays
    -   Can be created on the map by <kbd>Shift</kbd>-right clicking on a point to begin drawing
    -   Can be defined in source block using new `overlay` parameter
    -   Can be created from note frontmatter (found using existing `markerFile`, `markerFolder` and `markerTag` parameters) using `mapoverlay`
    -   Please see [the ReadME section](./README.md#Overlays) for syntax

**Comment by Moonbase59** [comment] 2021-05-25 18:18
Can’t make this work using 3.12.0. Whatever variant of `overlay` or YAML `mapoverlay` I use, the map simply vanishes. (Some error message would be good: Assume a user messes up a note using this, then goes to a map somewhere else, he’ll never find the cause of the map not functioning …)

It seems at least to _accept_ it (but not display an overlay) when using "double array notation" like
```
overlay: [[blue, [32, -89], 25, mi]]
```

You _are_ aware that YAML
```yaml
overlay: [blue, [32, -89], 25, mi]
```
and
```yaml
overlay:
  - [blue, [32, -89], 25, mi]
```
are _not the same?_ (The latter introduces an extra array around it)

**Comment by valentine195** [comment] 2021-05-25 18:21
Is there an error message in the console?

It should catch any bubbling errors and display it - not sure what's going on.

**Comment by Moonbase59** [comment] 2021-05-25 18:23
I reckon it wants the "array in array" version. If we’d leave out the `[]`, it would only return a string, which I would somehow not like—it’s a set of data elements, after all, and we don’t want to parse YAML ourselves. I’ll come back with the console messages soon …

**Comment by Moonbase59** [comment] 2021-05-25 18:43
I was using
```yaml
mapoverlay:
    - [green, [48.23875, 10.37595], 50, km]
```
in "People" note now, and it shows me this (heavily zoomed in):

![Auswahl_049](https://user-images.githubusercontent.com/3706922/119551351-d5d3b700-bd99-11eb-8dfa-0772ef6a7975.png)

Looks rather like 50 **metres** to me :-), wrong unit calculation?

**Comment by Moonbase59** [comment] 2021-05-25 18:48
Yep, it’s all metres, see:

I got:
```yaml
mapoverlay:
    - [green, [48.23875, 10.37595], 50, km]
    - [orange, [48.23875, 10.37595], 10000, m]
```
and this is shown:

![Auswahl_050](https://user-images.githubusercontent.com/3706922/119551992-8477f780-bd9a-11eb-869e-96df2320d95d.png)

**Comment by Moonbase59** [comment] 2021-05-25 19:00
More testing: Units seem okay, but it’s just too small by a factor of 1000!

**Comment by valentine195** [comment] 2021-05-25 19:03
I think this is actually because you have the `unit` set to "km"?

I do some scaling on overlays for use on image maps, but real world maps do not need this and I can fix it.

**Comment by valentine195** [comment] 2021-05-25 19:25
Please try 3.12.1 and let me know if it still occurs.

**Comment by valentine195** [comment] 2021-05-25 19:27
> I reckon it wants the "array in array" version. If we’d leave out the `[]`, it would only return a string, which I would somehow not like—it’s a set of data elements, after all, and we don’t want to parse YAML ourselves. I’ll come back with the console messages soon …

I'll add in a hook to parse this like I do the `marker` parameter if it is not defined via YAML.

Speaking of YAML - not sure if you saw the changelog, but I did add the ability to define _everything_ using YAML syntax, including the `marker`, `commandMarker`, etc.

**Comment by Moonbase59** [comment] 2021-05-25 19:32
Ah, yes. But if we have to _specify a unit_ (which we might want), it shouldn’t multiply/divide by the unit given in the code block. I think. This would mean if you change the unit on the map, you might have to change hundreds of notes. Very bad usability, ;-)

YAML: All params in YAML for the MAP note? But what if I have multiple maps on one note? (Which I have.) Otherwise _maybe_ a good idea, but taking into account that names like "unit" might have been used for other purposes — probably dangerous.

I’ll go and test 3.12.1 now :-)

**Comment by valentine195** [comment] 2021-05-25 19:36
> But if we have to specify a unit (which we might want), it shouldn’t multiply/divide by the unit given in the code block. I think. This would mean if you change the unit on the map, you might have to change hundreds of notes.

The image map actually requires this - the "simple" CRS essentially maps 1 pixel to 1 meter. In order to get accurate overlays and distances, I need to scale it by the provided unit. For real world maps this is not required, so 3.12.1 no longer does that scaling if it is not an image map.

> YAML: All params in YAML for the MAP note? But what if I have multiple maps on one note? (Which I have.) Otherwise _maybe_ a good idea, but taking into account that names like "unit" might have been used for other purposes — probably dangerous.

No, in the code source block. See [this](https://github.com/valentine195/obsidian-leaflet-plugin#yaml-syntax) section of the README.

**Comment by Moonbase59** [comment] 2021-05-25 19:58
> so 3.12.1 no longer does that scaling if it is not an image map.

Great, well done, again! Works fine.

> No, in the code source block.

I wondered if it was a typo ;-) But a good idea probably, YAML in the code block. Hope you use a good parser, YAML can be awfully complex.

---

3.2.1 works fine so far. Now for some thinking. Let me get another coffee …

- Seems you actually stack the overlays in z direction. This should be mentioned in the docs (put the smaller areas AFTER the larger ones in YAML, otherwise you won’t be able to access them).
- Seems you always keep the marker(s) _above_ the overlays. Very good!
- The cursor changes to a hand when over an overlay. What is supposed to happen?
- I wonder if it would make sense to add an additional "description" string field to the overlay data, that would be displayed in a tooltip when hovering. So one could put, say, "Home Zone" and "Nearby" on the overlays.
- I have to make a cheat sheet soon. We now have _so many_ variants of mouse-clicking and modifier keys that no one will be able to remember, at least not in a few weeks.
- Right-clicking an overlay says correctly "This overlay can’t be edited …", even when it comes from another note’s YAML. Very good.
- You seem to use HTML text color names. No one remembers these (at least I don’t), so maybe a link to a webpage might be good in the docs.
- While text color names are "natural", I think many of us programmer guys have a better ability to visualize #rrggbb colors in their head.
  - Allowing these of course invalidates the YAML (they are comments), except when put in apostrophes to become strings.
  - Would you think allowing the hash color notation would be good?
  - I guess we don’t need need the more fancy ones like `rgb()`, `rgba()` and so forth.
- As this plugin gets more complex every day, we need robust kind of error display if the map cannot be displayed. I love the brute-force "display a text" method Dataview uses, because it doesn’t vanish from the notifier before you have a chance to read and understand it. How do you feel about that?

**Comment by valentine195** [comment] 2021-05-25 20:10
> Seems you actually stack the overlays in z direction. This should be mentioned in the docs (put the smaller areas AFTER the larger ones in YAML, otherwise you won’t be able to access them).

I will add this to the docs, but I wonder if it's worth it for me to try to detect interferences and automatically layer them as needed.￼

> The cursor changes to a hand when over an overlay. What is supposed to happen?

Not sure - this is from Leaflet. 

> I wonder if it would make sense to add an additional "description" string field to the overlay data, that would be displayed in a tooltip when hovering. So one could put, say, "Home Zone" and "Nearby" on the overlays.

I like this, will add. 

> Would you think allowing the hash color notation would be good?

I didn't restrict anything here, just used Leaflet's native syntax. I believe they accept hashes - try it and let me know, if not I can add support. 

> As this plugin gets more complex every day, we need robust kind of error display if the map cannot be displayed. I love the brute-force "display a text" method Dataview uses, because it doesn’t vanish from the notifier before you have a chance to read and understand it. How do you feel about that?

Try to force an error - it should display properly now. Accidentally removed it during testing.

**Comment by Moonbase59** [comment] 2021-05-25 20:32
> try to detect interferences and automatically layer them as needed.

Not needed, I think.



> > The cursor changes to a hand when over an overlay. What is supposed to happen?
> 
> Not sure - this is from Leaflet.

Okay, it’s just the user expects it to be clickable in that case. Probaby no harm, since nothing happens.



> I like this, will add.

Incredible joy, working with you. I mean it.



> > Would you think allowing the hash color notation would be good?
> 
> I didn't restrict anything here, just used Leaflet's native syntax. I believe they accept hashes - try it and let me know, if not I can add support.

Unbelievable, it actually works if you put like `'#ff0000'`. Wow.

> Try to force an error - it should display properly now.

Wouldn’t repeat the whole code block, probably _just_ show the error line. Everything else, especially if not connected with the error, confuses the user. Like my error came from a people note’s YAML—no hint about that but a code block shown—confusion.

Please re-check my post above. I added some thoughts. Cheers!

**Comment by Moonbase59** [comment] 2021-05-25 20:45
>     * My original plan for maps was to use the `location` and `nearby` values in people and location notes to auto-create circle overlays _if_ the `nearby` value was found, simply using the data in `location` as the center and a general `overlaycolor` in the code block. I see that your solution is much more flexible, allowing to put many overlays plus different origins in a note’s YAML, but still somehow believe that for "the simple use case" my idea might shine. It’s just so much easier for a user to handle, _without_ having to remember all the `mapoverlay` syntax. And the techie could use _both_. Tell me what you think.

**Another of my crazy ideas:** Introduce two new settings for the map’s code block:
```yaml
autoOverlayYAML: nearby
autoOverlayColor: '#DAA520'
```
If these are set, check the given YAML name (`nearby`) in the found notes, and if such an entry exists, split the content ( `1.5 mi`) by whitespace into number and unit, and if the unit is okay (default to `unit` given in code block, if it exists), go autocreate an overlay for this note.

Boom! Best of both worlds!
What do you think?

**Comment by valentine195** [comment] 2021-05-25 20:51
> I think the more natural form of using "number blank unit" is appropriate from a usability standpoint. 

Doable, this is just the "easy" way since YAML auto-parses the number 😁

> My original plan for maps was to use the location and nearby values in people and location notes to auto-create circle overlays if the nearby value was found, simply using the data in location as the center and a general overlaycolor
> Another of my crazy ideas: Introduce two new settings for the map’s code block:

Yep, I can do this for an "easy" overlay generation. 

> Wouldn’t repeat the whole code block, probably just show the error line. Everything else, especially if not connected with the error, confuses the user. Like my error came from a people note’s YAML—no hint about that but a code block shown—confusion.

Yeah, I can remove the original text. I'll take a look at adding better error messaging.

**Comment by Moonbase59** [comment] 2021-05-25 20:53
If we get a concise doc on the zillion mouse+modkey functions, this will be the killer plugin! We neeed advertising … :grin:

**Comment by Moonbase59** [comment] 2021-05-25 21:05
Leflet is a sucker … even `['rgba(255,0,0,.2)', [48.23875, 10.37595], 10, km]` works, thus the nerds can make an overlay really unobtrusive, without you ever allowing an opacity parameter. Super.

**Comment by valentine195** [comment] 2021-05-26 14:08
> I wondered if it was a typo ;-) But a good idea probably, YAML in the code block. Hope you use a good parser, YAML can be awfully complex.

Just saw this - Obsidian exposed their YAML parser (which I believe just uses `yaml.js` anyway), so I use that.

I actually fall back to my original parsing method if it fails for some reason, but generally if the block _can't_ be parsed, my parser would also fail.

**Comment by Moonbase59** [comment] 2021-05-26 17:25
Starting to test, some first issues with empty maps shown. I _did_ change the mapoverlay YAML in the test files.

![Workspace 1_055](https://user-images.githubusercontent.com/3706922/119704313-cdda4c80-be57-11eb-9ce0-c85491b1480f.png)

![Workspace 1_056](https://user-images.githubusercontent.com/3706922/119704562-14c84200-be58-11eb-8fcd-f030f2878d6e.png)

**Comment by Moonbase59** [comment] 2021-05-26 17:35
Wonder if I have messed up something. Here is the YAML from my one test note:

```yaml
---
location: [48.23875,10.37595]
mapmarker: Family
# stack smaller areas UNDER large ones or you won’t be able to access them!
mapoverlay:
    #- [GoldenRod, [48.23875, 10.37595], 10 km]
    #- ['#DAA520', [48.23875, 10.37595], 10 km]
    #- ['rgb(218, 165, 32)', [48.23875, 10.37595], 10 km]
    - ['rgba(218, 165, 32, .6)', [48.23875, 10.37595], 10 km, ""]
    - [green, [48.23875, 10.37595], "50 m", "Home Zone"]
birthday: 1959-07-19
tags: family
nearby: 100 km
---
```

**Comment by valentine195** [comment] 2021-05-26 17:36
No, it is me - I see the error, should have a fix soon.

**Comment by valentine195** [comment] 2021-05-26 17:43
Please try 3.13.1

**Comment by Moonbase59** [comment] 2021-05-26 17:49
Fantanstic. Will test in a few minutes.

Meanwhile, another bug: `overlayTag: nearby` and `overlayColor: red` function real great, _but_ they picked up something from my Templates folder. These should of course also be _restricted_ to whatever search terms where specified. "Auto" is great but one should to be able to specify "where". Imagine a guy I know that has around 12k notes, and the unneccessary performance hit (or odd overlays creeping up from templates).

**Comment by valentine195** [comment] 2021-05-26 17:53
`overlayTag` only looks at notes that are specified using `markerFile`, `markerFolder` and `markerTag` - does your template file have one of the tags? It was probably being grabbed already, but a marker wasn't being generated due to incorrect syntax (my guess).

**Comment by Moonbase59** [comment] 2021-05-26 18:04
Darn, you’re right! There was a forum post I pre-edited in my `+Inbox` folder which I had included in the map for testing, and _that_ of course had `nearby: 500 km` and `location:` set!

One has to be so careful …

> With great power comes great responsibility.
> <cite>— Peter Parker</cite>

:rofl:

**Comment by Moonbase59** [comment] 2021-05-26 18:18
Seems all you declared "fixed" in 3.13.0 _are_ now.

![Schreiben - Obsidian v0 12 3_057](https://user-images.githubusercontent.com/3706922/119710368-8efbc500-be5e-11eb-9d99-852544f3172f.png)

3.13.1 seems to handle mapoverlays from notes nicely. It draws 3 (!) overlays around my house: The topmost (red) being from "nearby" , the "golden-ish" one from a mapoverlay in my note, and there is even a very small 50m one around my house.

Sad to say, but from a usability standpoint now comes stacking into play again: When hovering over "red", I see "Matthias C. Hormann: Nearby" (beautiful!) but I can’t see the text for the two mapoverlays (golden & green)—"Whatever" and "Home Zone".

I would say "stack the smaller on top of the larger" but that only functions if they all have the same origin (which they might _not_ have, due to all the new flexibility). I wonder how that could be done with, say, 3 people living relatively nearby, but each having a greater "nearby" radius. One might be hidden within the other’s circle. Any ideas?

**Comment by valentine195** [comment] 2021-05-26 18:21
This is tough because it's a DOM stacking problem. They're drawn in the DOM as defined, and only the last drawn element will be interactable if they're obscured.

Would probably have to do this: 

> try to detect interferences and automatically layer them as needed.

**Comment by Moonbase59** [comment] 2021-05-26 18:28
You’re a genius. And together we’re unbeatable. This, paired with all the linking, tagging and YAML frontmatter Obsidian offers, is _already_ the most useful (and _usable_) mapping app (well, plugin) I know of. Great job!

**Comment by Moonbase59** [comment] 2021-05-26 18:54
Yet another idea: When showing the overlayTag circle, could you also show its radius (in whatever unit it was in their YAML, for friends in several countries: I’d use `mi` in the U.S., `km` in Europe)?

Like maybe `Matthias C. Hormann: Nearby (25 km)` or `Physician: Nearby (0.5 mi)`? For radiuses varying by note, this might be a good user experience.

**Comment by valentine195** [comment] 2021-05-26 19:01
## 3.13.2

- Fixed issue with parsing of mapoverlay frontmatter tag
- Immutable overlays now render in order of largest -> smallest, so smallest are always interactable
- Added display of `overlayTag` distance in overlay popup
- Fixed issue where drawn overlays were being re-rendered incorrectly when the map was re-opened on real world maps

**Comment by Moonbase59** [comment] 2021-05-26 19:15
Not 100%, yet. ;-)

I have my place (green marker) with a nearby radius of 10 km, a mapoverlay (YAML, in note) of 50 m. Both have the same origin. Near by is one of my physicians (red marker) who, in turn, has a nearby radius of 100 m.

Now the `Matthias C. Hormann: Nearby (10 km)` "hides" access to both my 50 m "Home Zone" and the physician’s 100 m zone. Also, in theory, the shop at top right (orange marker) would be hidden, if it had a `nearby:` entry (which it doesn’t).

![Schreiben - Obsidian v0 12 3_058](https://user-images.githubusercontent.com/3706922/119718101-7512b000-be67-11eb-8277-a5a2e6ba9fa0.png)

![Schreiben - Obsidian v0 12 3_059](https://user-images.githubusercontent.com/3706922/119718128-7b089100-be67-11eb-904e-dca48cba635d.png)

Thoughts?

**Comment by valentine195** [comment] 2021-05-26 19:20
Whoops - I'm just comparing the numbers, not converting between units. Will be fixed soon 😳

**Comment by valentine195** [comment] 2021-05-26 19:26
Please try 3.13.3

**Comment by Moonbase59** [comment] 2021-05-26 19:41
Looks great so far, but the tooltips for the smaller zones are shown only a fraction of a second if "on" a larger zone, barely readable before they vanish.

I’m wondering if we should also show the `(radius)` for overlays from `mapoverlay` YAML entries.

Pro:
- It would make the experience more seamless.

Con:
- Users might want to put their own text. Then again, why not show the shown radius, too?

**Comment by valentine195** [comment] 2021-05-26 19:47
I can also just make it _always_ display the radius, regardless if there is a description.

**Comment by Moonbase59** [comment] 2021-05-26 19:49
Yep, why not. But _if_ there is a description, you’ll also display that, right?

**Comment by valentine195** [comment] 2021-05-26 19:51
Yes - the radius would just be appended to the end like it is now for the `overlayTag`.

**Comment by Moonbase59** [comment] 2021-05-26 19:55
Sounds good.

Re the popups:
- If you come into the map window from outside it, they’ll stay as long the mouse hovers.
- If you move within the map window, and come hovering over a zone that’s within another zone, it displays the smaller zone’s popup only for a fraction of a second.

Odd, but maybe it helps.

**Comment by valentine195** [comment] 2021-05-26 19:59
I think this is a timing issue - the pop ups are actually 1 pop up being moved around, and there's a half-second delay before they disappear. The delay must not be getting canceled properly.

**Comment by Moonbase59** [comment] 2021-05-26 20:00
![Peek 2021-05-26 21-59](https://user-images.githubusercontent.com/3706922/119723446-be65fe00-be6d-11eb-9ed2-3d8b5eefa9d8.gif)

**Comment by valentine195** [comment] 2021-05-27 14:27
> If you move within the map window, and come hovering over a zone that’s within another zone, it displays the smaller zone’s popup only for a fraction of a second.
> I can also just make it always display the radius, regardless if there is a description.

Should be fixed in 3.13.4

**Comment by Moonbase59** [comment] 2021-05-27 17:42
Works perfect, thanks again!

**Comment by Moonbase59** [comment] 2021-05-27 18:00
I’m impressed. You even allow `overlayTag: "In der Nähe"` ("near by" in German, people might use such fancy stuff).

Only you seem to convert to "sentence" case for displaying it. This is probably okay for English and actually nice if you use a one-word tag like "nearby", but might not work out for other languages. You convert my crazy YAML entry "In der Nähe" to "In der **n**ähe", and with languages like Chinese, Korean, Japanese that might totally break, because they have real crazy rules about word separation und upper-/lowercasing.

**Comment by valentine195** [comment] 2021-05-27 18:04
> Using 0.1 mi produces an error

This is due to my regex, didn't catch the floats properly. Will fix ASAP

> might not work out for other languages.
Good point - will remove.

**Comment by Moonbase59** [comment] 2021-05-27 19:16
See https://github.com/valentine195/obsidian-leaflet-plugin/issues/31#issuecomment-849873998, I forgot that it’s closed already.

**Comment by Moonbase59** [comment] 2021-05-27 19:22
> I wonder if maybe just doing a `.charAt(0).toUpperCase()` might be enough. It _seems_ to support Unicode.

Did you see this? It was an edit, sorry. It wouldn’t be tragic, it’s ok as it is now, but just for thinking.

**Comment by Moonbase59** [comment] 2021-05-27 19:27
It cant parse "nearby" of `.1 mi`. But to be honest, I’d neglect it. Users _should_ use a leading zero in such cases.

**Comment by Moonbase59** [comment] 2021-05-27 20:02
We should have a list of supported units. By pure chance I found that you also do `ft`. Just I like to keep my Dataview snippets in sync. ;-)

**Comment by valentine195** [comment] 2021-05-27 20:12
> I wonder if maybe just doing a `.charAt(0).toUpperCase()` might be enough. It _seems_ to support Unicode.

I will probably just leave it to the user to format it themselves. 

> We should have a list of supported units. By pure chance I found that you also do ft. Just I like to keep my Dataview snippets in sync. ;-)

Please see src/utils/constants.ts for a list of length names that will work until I can add this to the docs.

**Comment by Moonbase59** [comment] 2021-05-27 20:22
> see src/utils/constants.ts for a list of length names

Now that’s what I call _Overfeaturitis_ :rofl:

**Comment by Moonbase59** [comment] 2021-06-04 17:45
Regarding filtering the overlays from notes: I’ve been talking this through with some users again, and there seems to be this general consensus:
- _Most_ mapoverlays specified in notes will have something to do with its marker, i.e. specifying stations on a trail (the marker showing its starting point), or specifying interseting locations near a marker (say, bathing jetties in a bathing lake, where the marker shows the entry point). In these cases, still showing the overlays when the marker is disabled by filtering is felt distracting, and they should be switched off in the display.
- Some (few) users might want to define/collect mapoverlays in a note, to always show them on a map, not necessarily requiring a marker.

So I think it might be a good idea to have some boolean option like `filterOverlaysWithMarkers`, maybe per map instance (in order not to bloat the individual notes where the data is gotten from). If `true`, which could be the "natural default", overlays for disabled markers would _not_ be shown.

A real-world example, shows two "places-to-check" (turqoise) and one "sports" (violet) marker and their overlays (from their notes):

![Schreiben - Obsidian v0 12 3_088](https://user-images.githubusercontent.com/3706922/120842487-09b69580-c56d-11eb-836b-8852ac2c10e6.png)

![Schreiben - Obsidian v0 12 3_089](https://user-images.githubusercontent.com/3706922/120842656-484c5000-c56d-11eb-93d4-711a280eef75.png)

Understandable? Thoughts?

**Comment by valentine195** [comment] 2021-06-04 19:57
I think this makes sense. Will add in the next release.

**Comment by valentine195** [comment] 2021-06-07 18:37
> I think this makes sense. Will add in the next release.

Fixed in 3.15.0

**Comment by Moonbase59** [comment] 2021-06-07 22:33
Couldn’t test with 3.15.0, since no markers are shown anymore (see https://github.com/valentine195/obsidian-leaflet-plugin/issues/84#issuecomment-856303921).

**Comment by Moonbase59** [comment] 2021-06-08 20:33
Just went through this monster thread again, and apart from GeoJSON areas (which might be overkill), everything seems fixed now. Maybe we can close this?

**Comment by valentine195** [comment] 2021-06-08 20:37
Agreed, but I'll add an issue about GeoJSON - I actually forgot about it.

**Closed** 2021-06-08 20:38 UTC
Labels: enhancement
